import { faker } from '@faker-js/faker'
import mock from '../../utils/e2e'

describe('Request transport service', () => {
  it('successfully login and request GOODS transport service', () => {
    cy.login()
    cy.intercept('POST', '**/request/transport_service/', mock()).as('request/transport_service')
    cy.visit('/')
    cy.findByText('Am o solicitare').click()
    cy.findByText('Servicii').click()
    cy.get('#resource_services').click()
    cy.findAllByText('Adaugă').first().click()
    cy.get('#description').type(faker.commerce.productName())
    cy.get('#weight_capacity').type(100)
    cy.get('#weight_unit').type('l')
    cy.get('#has_refrigeration_true').check()
    cy.get('select[name="from_county"').select(1)
    cy.get('#from_city').type(faker.company.companyName())
    cy.get('select[name="to_county"').select(1)
    cy.get('#to_city').type(faker.company.companyName())
    cy.get('form button').click()
    cy.wait('@request/transport_service')
  })

  it('successfully login and request PEOPLE transport service ', () => {
    cy.login()
    cy.intercept('POST', '**/request/transport_service/', {}).as('request/transport_service')
    cy.visit('/')
    cy.findByText('Am o solicitare').click()
    cy.findByText('Servicii').click()
    cy.get('#resource_services').click()
    cy.findAllByText('Adaugă').eq('1').click()
    cy.get('#available_seats').type(2)
    cy.get('#description').type(faker.commerce.productName())
    cy.get('#has_disabled_access_true').check()
    cy.get('#pets_allowed_true').check()
    cy.get('select[name="from_county"').select(1)
    cy.get('#from_city').type(faker.company.companyName())
    cy.get('select[name="to_county"').select(1)
    cy.get('#to_city').type(faker.company.companyName())
    cy.get('form button').click()
    cy.wait('@request/transport_service')
  })
})
